### PR TITLE
[WIP] add ppc64le support to travis.yml

### PR DESCRIPTION
**Pull request by seth-priya**
https://github.com/razee-io/RemoteResourceS3/issues/164

### CODE REVIEW

**Comment by alewitt2** [comment]
not sure i understand what you are doing here.. all you have changed is the removing a linter for ppc. where are you pushing a ppc based image? how does this create a ppc image?

**Comment by seth-priya** [comment]
so @alewitt2 thanks for having a look. I can explain - I am essentially adding ppc64le support with the below lines
 arch:
  - amd64
  - ppc64le
this results in a separate travis job being triggered for ppc64le like the one here https://travis-ci.com/github/razee-io/RemoteResourceS3/jobs/427810602 , https://travis-ci.com/github/razee-io/RemoteResourceS3/jobs/427810602#L46

and this is where the docker image for ppc64le is being builthttps://travis-ci.com/github/razee-io/RemoteResourceS3/jobs/427810602#L46
similar to what the amd64 job is doing.

There were no special changes needed for ppc64le except the linter changes which were needed as shellcheck in not available currently.

**Comment by alewitt2** [comment]
i guess i just dont understand how changing the travis arch also changes the docker image. the docker image is based on node-alpine. I would have thought you would need to change the underlying docker image to do what you are wanting? Maybe i dont understand what your wanting?

**Comment by seth-priya** [comment]
so the node:lts-alpine image that is being used is multiarch , that is if do a pull and inspect on ppc64le, it will give this

docker pull node:lts-alpine
lts-alpine: Pulling from library/node
9a8fdc5b6983: Already exists
5eaad9f3fe5c: Pull complete
3a736cd52a05: Pull complete
7b48853f922b: Pull complete
Digest: sha256:5a940b79d5655cc688cfb319bd4d0f18565bc732ae19fab6106daaa72aeb7a63
Status: Downloaded newer image for node:lts-alpine
docker.io/library/node:lts-alpine

docker inspect node:lts-alpine | grep -i arch
        "Architecture": "ppc64le",

that is pull the ppc64le image. On the other hand, the same command will pull an amd64 image on amd64. This is possible due to the use of manifests
Reference: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

Since the travis job for ppc64le will do a native build on a ppc64le env. it will pull the correct image (i.e. ppc64le image) and hence build the correct one as well (i.e ppc64le)

So, we are good till the point of the build, I have not been able to check the "docker push" functionality , but we may have to change the tag for Power, I will work on confirming that.

**Comment by alewitt2** [comment]
ok. that makes sense. yes you will need to make sure you are not overwriting the amd image when doing the docker push

**Comment by seth-priya** [comment]
@alewitt2 so for handling the "docker push" part, it seems that I will need to use the travis-ci multi-stage builds and construct and push the manifest as part of the final stage. Just to give you some idea of what I am trying, I have a "working" travis.yml here https://github.com/sethp-collab/RemoteResourceS3/blob/master/.travis.yml. I can probably try to move the logic for building the image and creating the multiarch manifest if that sounds fine to you and will need to do some more testing, but just wanted to your initial thoughts and feedback on this approach, thanks!

**Comment by seth-priya** [comment]
Here is a sample travis run (I have currently added some extraneous test code to test the image push_ https://travis-ci.com/github/sethp-collab/RemoteResourceS3/builds/202363593 @alewitt2

**Comment by alewitt2** [comment]
@ seth-priya can you help me understand why this is necessary?

**Comment by seth-priya** [comment]
so @alewitt2 if your question is about multistage builds, it was necessary because we are constructing and pushing the manifest in the third and final stage, once both the amd64 and ppc64le images are built and published. There is more info on stages here https://docs.travis-ci.com/user/build-stages/ but essentially "Build stages is a way to group jobs, and run jobs in each stage in parallel, but run one stage after another sequentially.", this is what we needed for our scenario. Please let me know if that does not make sense or you have other suggestions or thoughts? thanks!

**Comment by alewitt2** [comment]
i dont know enough about this to push back right now. i will need to do some more investigation before i feel comfortable approving. Is there a tight time box on this? i am thinking i might have time the 1st or 2nd week of December to look at this again

**Comment by seth-priya** [comment]
thanks @alewitt2 , please do let me know if I can help with any additional details on this. I did look at alternatives and there are a few things that can be considered in the longer term to simplify parts of the build procedure (like docker buildx and GitHub Actions) but unfortunately they are not fully supported on Power as at this point in time though some of it is in the works. 

On your question about the timelines, I am adding @gerrith3 for his comments, one of the use cases that we currently have for this is as a dependency for the overall redhat-market-operator support on Power that we are trying to work through.

If it helps we can get onto a call or something to discuss more specific details on some of this. (cc @gerrith3)

**Comment by alewitt2** [comment]
yeah please set up a call for after thanksgiving week and hopefully you can help me understand a bit better. im @lewitt2 on slack. please also add @rak

**Comment by alewitt2** [comment]
So i did a little research on travis stages.. tldr: jobs within a stage run in parallel, stages run sequentially. If a stage fails, subsequent stages wont run.

Based on that info, i think we should set up the stages as such:
```
jobs:
  include:
    - stage: "Build Multi-Arch Images"         
      name: "Build amd64 image"
      script: all the logic...
    - name: "Build ppc64le image"
       script: all the logic...
    - stage: "Build Multi-Arch Manifest"
      name: "Create and push multi-arch manifest"
      script: all the logic...
```

**Comment by seth-priya** [comment]
Closing this , will open a new one with the discussed approach with the final set of changes

**Pull request closed without merging**
